set(CTEST_PROJECT_NAME "STRUMPACK")
set(CTEST_NIGHTLY_START_TIME "01:00:00 PST")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=STRUMPACK")
set(CTEST_DROP_SITE_CDASH TRUE)
